import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useState } from 'react'
import dynamic from 'next/dynamic'

const ModukAccordion = dynamic(() => import('@moduk/react').then(Moduk => Moduk.ModukAccordion), {
  ssr: false,
  loading: () => <p>Loading...</p>,
})

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [items, setItems] = useState([
    {
      heading: "Writing well for the web",
      content: "This is the content for Writing well for the web.",
      expanded: true,
    },
    {
      heading: "Writing well for specialists",
      content: "This is the content for Writing well for specialists.",
    },
  ]);

  const [inputs, setInput] = useState({ heading: '', content: '' })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Demo</h1>
        <div>
          <div>
            <label htmlFor='heading'></label>
            <input type="text" id="heading" value={inputs.heading} onChange={(evt) => {
              setInput({
                ...inputs,
                heading: evt.target.value
              })
            }} />
          </div>
          <div>
            <label htmlFor='content'></label>
            <textarea id="content" value={inputs.content} onChange={(evt) => {
              setInput({
                ...inputs,
                content: evt.target.value
              })
            }} />
          </div>
          <button onClick={() => {
            setItems([inputs, ...items])
            setInput({ heading: '', content: '' })
          }}>Add</button>
        </div>
        <ModukAccordion items={items} />
      </main>
    </>
  )
}
